/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\MZ\\Desktop\\vuepress-blogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-a6c4d36c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6c4d36c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-d45d87fa",
    path: "/leading/css/css-base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d45d87fa").then(next)
    },
  },
  {
    name: "v-9ecbc136",
    path: "/leading/css/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9ecbc136").then(next)
    },
  },
  {
    name: "v-dc1ecfa6",
    path: "/leading/js/js-base.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc1ecfa6").then(next)
    },
  },
  {
    name: "v-1275c954",
    path: "/leading/network/Browser%E8%A7%A3%E6%9E%90%E6%96%87%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1275c954").then(next)
    },
  },
  {
    path: "/leading/network/Browser解析文件.html",
    redirect: "/leading/network/Browser%E8%A7%A3%E6%9E%90%E6%96%87%E4%BB%B6.html"
  },
  {
    path: "/leading/network/Browser解析文件.html",
    redirect: "/leading/network/Browser%E8%A7%A3%E6%9E%90%E6%96%87%E4%BB%B6.html"
  },
  {
    name: "v-4f52a2a6",
    path: "/leading/network/cross-domain.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f52a2a6").then(next)
    },
  },
  {
    name: "v-0dfcf2b8",
    path: "/leading/network/web%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0dfcf2b8").then(next)
    },
  },
  {
    path: "/leading/network/web工作原理.html",
    redirect: "/leading/network/web%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86.html"
  },
  {
    path: "/leading/network/web工作原理.html",
    redirect: "/leading/network/web%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-46939fc6",
    path: "/life/six/618.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46939fc6").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]